### ISSUE TITLE
Security Issue - remove key.txt

### ISSUE THREAD

**Issue by brean** [BrianSherif/NO-MAD#1]
I think you should at least revoke your key with skyscanner and ideally remove the key.txt from this github repo (add it to your .gitignore file). Keep in mind that only deleting the file will keep it in the git history.

**Comment by BrianSherif** [comment]
Greetings, 
Thank you for your concern. 
The API key is revoked before release by Skyscanner for security reasons. 
This repo is only used for portfolio purposes.

**Comment by brean** [comment]
Hi, thank you for taking this seriously! 
The key was NOT revoked 2 days ago!
I was able to use this key and get some data from skyscanner with it.
I think you should revoke it manually if you did not already do so.

**Comment by BrianSherif** [comment]
Greetings, 
Thank you for your reply, I have removed the key. I have also proceeded to remove it from the history. 
If you find any further issues please feel free to report them 
Thank you once again.
